// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const logo = function (name, url = '') {
  return (`<div class="sidebar-logo-item">
    ` + (
      (url != '') ?
      `<img src="${url}" width="32" height="32" alt="logo" />` : ``
    ) + `
    <text>${name}</text>
    </div>`);
};

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Actually-used sidebars
  default: [
    {
      type: 'autogenerated',
      dirName: 'default',
    }
  ],
  contributionSidebar: [
    /*{
      type: 'html',
      value: logo("Contribution"),
      defaultStyle: false,
    },*/
    {
      type: 'autogenerated',
      dirName: 'contribution',
    }
  ],
  polarFrankieSidebar: [
    {
      type: 'autogenerated',
      dirName: 'frankie',
    }
  ],
};

export default sidebars;
